### ISSUE TITLE
Implement Brackets

### ISSUE THREAD

**Issue by Kthewarlord** [iq180-netcentric/core-logic#2]
Implement the use of Brackets in core-logic

**Comment by Samuraiwarm** [comment]
- [x] validateForDisplay

- [x] highlightWrongLocation : needs more discussion

- [x] calculate

- [x] generate : ideal case - insert `n` brackets at random places

**Comment by Samuraiwarm** [comment]
Done @Kthewarlord please test thx
If all OK, please close this issue
